### PR TITLE
Drop Python 2 support

### PR DESCRIPTION
**Pull request by bmw**
I based the changes in this PR on 4e5e4b9e18b370dbab718bca9c50c1758cf3c5aa and https://github.com/certbot/certbot/pull/8591.

### CODE REVIEW

**Review by ohemorange — DISMISSED** [review]

**Comment by ohemorange** [comment]
do we want to put something in the changelog about this?

**Comment by bmw** [comment]
The release process in this repo is at least a couple years behind Certbot's. In particular, we have to manually update the changelog so I've just been writing it before doing the release like we used to with Certbot.

I just created https://github.com/certbot/josepy/pull/80 to help us remember to do that.

**Comment by ohemorange** [comment]
Oh... wow... ye olden days. It still might make it easier to update as we go, per PR?

**Comment by bmw** [comment]
You're right. I was initially hesitant to do that because I thought the partial changelog like we have in Certbot would make me more likely to forget that it needs to be manually updated, but I think https://github.com/certbot/josepy/pull/80 should take care of that.

**Review by ohemorange — APPROVED** [review]

**Pull request merged**
