### PR TITLE
EC signature padding

### PR DESCRIPTION
**Pull request by commonism**
The r||s encoding is wrong for ec keys and signatures with leading zeros.
This results in bad signatures, I've come across:

"Parse error reading JWS: EC public key has incorrect padding"
"failed to unmarshal JWK: square/go-jose: invalid EC public key, wrong length"

Leading zero happens very frequently for ES512, rare with ES256.

This was already wrong in my proposal for r||s and just got ported to using cryptography api.

int.to_bytes requires python >= 3.2
bytes.fromhex python >= 3.0
so they are safe to use here.

### CODE REVIEW

**Comment by commonism** [comment]
Had some issues with the CI, force pushed to keep things tidy.

**Comment by bmw** [comment]
@atombrella or @adferrand, do either of you have the time and interest to take a look at this since you reviewed https://github.com/certbot/josepy/pull/51?

**Comment by adferrand** [comment]
For sure I will review it in the next days. I already looked at it quickly this week and it seemed good.

**Comment by bmw** [comment]
Thanks Adrien!

I'm assigning you for now but if you end up not being able to get to it for whatever reason, just let me know.

**Review by adferrand — APPROVED** [review]
Thanks a lot @commonism, this LGTM. I appreciate in particular the updated test cases that will catch this error if future developments would break again when leading zeros are involved, since this is something quite hard to catch without unit tests.

**Pull request merged**
