### PR TITLE
Deprecate magic_typing

### PR DESCRIPTION
**Pull request by bmw**
Fixes https://github.com/certbot/certbot/issues/8660.

### CODE REVIEW

**Review by alexzorin — APPROVED** [review]
I'd be curious to know why `magic_typing_test.py` passes under `pytest` but not as a `unittest` main program. But since this happens on `master` too, LGTM.

**Comment by bmw** [comment]
Strange. What command are you using to run the tests? I wasn't able to cause them to fail.
```
(venv) ~/Development/github.com/certbot/josepy(master ✔) git rev-parse HEAD
fff286cc47493c817f98771ca0d2a302b79b26fb
(venv) ~/Development/github.com/certbot/josepy(master ✔) python src/josepy/magic_typing_test.py 
..
----------------------------------------------------------------------
Ran 2 tests in 0.040s

OK
(venv) ~/Development/github.com/certbot/josepy(master ✔) python -m unittest josepy.magic_typing_test
..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK
```

**Comment by alexzorin** [comment]
Ah. Maybe I screwed something up when setting up the repository. 

    (venv)
    alex at x1 in ~/devel/josepy (master)
    $ git rev-parse HEAD
    fff286cc47493c817f98771ca0d2a302b79b26fb
    
    (venv)
    alex at x1 in ~/devel/josepy (master)
    $ python -V
    Python 3.8.5

    (venv)
    alex at x1 in ~/devel/josepy (master)
    $ which python
    /home/alex/devel/josepy/venv/bin/python

    (venv)
    alex at x1 in ~/devel/josepy (master)
    $ python src/josepy/magic_typing_test.py
    E.
    ======================================================================
    ERROR: test_import_failure (__main__.MagicTypingTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "src/josepy/magic_typing_test.py", line 38, in test_import_failure
        from josepy.magic_typing import Text  # pylint: disable=no-name-in-module
      File "/home/alex/devel/josepy/src/josepy/__init__.py", line 41, in <module>
        from josepy.interfaces import JSONDeSerializable
      File "/home/alex/devel/josepy/src/josepy/interfaces.py", line 6, in <module>
        from josepy import errors, util
      File "/home/alex/devel/josepy/src/josepy/util.py", line 4, in <module>
        import OpenSSL
      File "/home/alex/devel/josepy/venv/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/home/alex/devel/josepy/venv/lib/python3.8/site-packages/OpenSSL/crypto.py", line 14, in <module>
        from cryptography import utils, x509
      File "/home/alex/devel/josepy/venv/lib/python3.8/site-packages/cryptography/utils.py", line 9, in <module>
        import typing
    ModuleNotFoundError: import of typing halted; None in sys.modules

    ----------------------------------------------------------------------
    Ran 2 tests in 0.066s

    FAILED (errors=1)

**Comment by bmw** [comment]
I see! I think the cause for the difference is you have a newer version of `cryptography` than I do. The newer version imports `typing` which causes our test for the case where `typing` isn't available to blow up unexpectedly.

I'll create PRs to fix this and the equivalent test for `acme.magic_typing`.

**Comment by alexzorin** [comment]
OK, that makes sense. My venv cryptography is installed at a higher version than in the constraints file. 

At the same time, `pytest` appears to pass on the same tests, which is slightly disconcerting if I'm reviewing these :laughing:.

    src/josepy/magic_typing.py::FLAKE8 SKIPPED (file(s) previously passed FLAKE8 checks)              [ 77%]
    src/josepy/magic_typing_test.py::FLAKE8 SKIPPED (file(s) previously passed FLAKE8 checks)         [ 77%]
    src/josepy/magic_typing_test.py::MagicTypingTest::test_import_failure PASSED                      [ 78%]
    src/josepy/magic_typing_test.py::MagicTypingTest::test_import_success PASSED                      [ 78%]

**Comment by bmw** [comment]
My understanding of that is minor differences in how `pytest` and `unittest` import code before running tests. That stack trace is happening in `src/josepy/__init__.py` which I imagine `pytest` ran before running the code in `test_import_failure`. We've seen other examples like https://github.com/certbot/certbot/pull/8630#issuecomment-772819281.

Differences in test behavior like this aren't ideal, however, I'm personally not too worried about it. We have `tox` configured to run our tests using `pytest` and instruct our packagers to use `pytest` as well. See https://certbot.eff.org/docs/packaging.html#notes-for-package-maintainers.

Do you think this is OK or do you think we should do something else about this?

**Pull request merged**
